# Service to expose web frontend
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: app
  labels:
    app: metrics
spec:
  selector:
    group: api
  ports:
  - name: metrics
    protocol: TCP
    port: 9102
    targetPort: 9102

---
# API service version 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: app
  labels:
    app: api-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-v1
  template:
    metadata:
      labels:
        group: api
        app: api-v1
      annotations:
          sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: api
        image: nicholasjackson/fake-service:v0.20.0
        ports:
        - containerPort: 9090
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:9090"
        - name: "NAME"
          value: "api-v1"
        - name: "MESSAGE"
          value: "Response from API v1"
