name: Go

on:
  [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Code Tests
      run: make test
    
  functional_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Setup Functional Tests
      run: |
        curl https://shipyard.run/install | bash
        shipyard run ./shipyard

    - name: Run Functional Tests
      run: |
        eval $(shipyard env)
        make functional_test